### PR TITLE
Answers to Question.txt

### PR DESCRIPTION
**Pull request by Dantech12**
[Owusu_5201040708.txt](https://github.com/osammy820/Software_Engineering_Level_300/files/10772641/Owusu_5201040708.txt)

### CODE REVIEW

**Comment by Dantech12** [comment]
This was really difficult

**Comment by Dantech12** [comment]
[Owusu_5201040708.txt](https://github.com/osammy820/Software_Engineering_Level_300/files/10772636/Owusu_5201040708.txt)

**Comment by MeshachOpoku** [comment]
Am done with it Opoku_5200104020

**Comment by Acquah-Albert-Ocran** [comment]
please sir, am done with the work
5201041213_Acquah

**Comment by AmoatengPeter** [comment]
please sir, am done with the work
5201040426_Amoateng

**Comment by AmoatengPeter** [comment]
please sir, am done with the work.
5201040426_Amoateng

**Comment by richmondberchie** [comment]
Done Richie

**Pull request closed without merging**
