### PR TITLE
i am done with the assignment

### PR DESCRIPTION
**Pull request by Dantech12**

### CODE REVIEW

**Comment by BenjaminFM** [comment]
Benjamin Frimpong Mensah 5201450017

**Comment by IddiSuliaNakuu** [comment]
please sir, am done with the work

**Comment by Aggressive-Mohammed** [comment]
mohammed

**Comment by OPPONGPATRICK1** [comment]
done
5201040073_Oppong

**Comment by Acquah-Albert-Ocran** [comment]
please sir, am done with the work
5201041213_Acquah

**Comment by sarfo-charles** [comment]
Done

**Comment by AmoatengPeter** [comment]
please sir am done with the work.
5201040426_Amoateng

**Comment by kingsmart101** [comment]
[osei-ampofo_5201040412.txt](https://github.com/osammy820/Software_Engineering_Level_300/files/10793246/osei-ampofo_5201040412.txt)
sir am done

**Pull request closed without merging**
